version: '3.7'

services:

   pypiserver:
      build: ./pypi
      container_name: pypiserver
      hostname: pypiserver
      restart: always
      environment:
         DEBUG: 'false'
      volumes:
         - ./pypiserver-server-alpine-3.9.4-vol/packages:/srv/packages:ro
      ports:
         - 8080:8080