# Use Case: Basic Installation
services:
   # Project URL: https://github.com/mariadb
   # Docs URL: https://mariadb.com/kb/en/documentation/
   custom-mariadb-8.3:
      image: mariadb:10.8.3
      container_name: custom-mariadb-8.3
      restart: always
      networks: ['demo']
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: acme
         MYSQL_USER: test
         MYSQL_PASSWORD: test
      command: --default-authentication-plugin=mysql_native_password
      volumes:
         # *** MySQL configuration ***
         - ./example.sql:/docker-entrypoint-initdb.d/1.sql
         # *** Volume configuration ***
         - ./mariadb-data:/var/lib/mysql:rw
      ports:
         - 3306:3306

   # Project URL: https://github.com/TimWolla/docker-adminer
   # Docs URL: https://hub.docker.com/_/adminer/
   adminer:
      image: adminer:4.17.1
      restart: always
      container_name: adminer
      networks: ['demo']
      ports:
         - 8080:8080

networks:
   demo:
      name: demo
      driver: bridge