version: '3.7'

services:

   registry:
      #image: registry
      image: registry:2.8.1
      container_name: registry
      restart: always
      environment:
         REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      volumes:
         - ./vol-registry/registry:/data
         #- ./vol-registry/opt:/opt/registry/config.yml
      ports:
         - "1000:5000"