services:
    # Project URL: 
  # Docs URL: 
    ollama:
      image: ollama/ollama:0.1.34
      container_name: "ollama"
      restart: always
      networks: ['demo']
      ports:
        - 11434:11434
      volumes:
        - ./ollama-data:/root/.ollama

    openWebUI:
      image: ghcr.io/open-webui/open-webui:main
      container_name: "ollama"
      restart: always
      networks: ['demo']
      environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      # Run ollama on the docker host
      #- OLLAMA_BASE_URL=http://host.docker.internal:11434
      ports:
        - 3000:8080
      extra_hosts:
        - "host.docker.internal:host-gateway"
      volumes:
        - ./open-webui-data:/app/backend/data
      depends_on:
        - ollama

volumes:
  ollama-data:
  open-webui-data:

networks:
  demo:
    name: demo
    driver: bridge