version: '3.7'

services:

   registry:
      #image: registry
      image: registry:2.8.1
      container_name: registry
      restart: always
      environment:
         REGISTRY_STORAGE_DELETE_ENABLED: true
      volumes:
         - ./vol-registry/registry:/var/lib/registry
         #- ./vol-registry/opt:/opt/registry/config.yml
      ports:
         - "1000:5000"
